
name: paper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  paper:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
    - name: Install
      run: |
        pip install .
    - name: Install paper depends
      run: |
        pip install -r paper/requirements.txt
    - name: Run paper experiments
      run: jupyter nbconvert --ExecutePreprocessor.timeout=-1 --execute "paper/Paper-*.ipynb" --to notebook --output-dir='temp' --clear-output
